name: Deploy ASP.NET Core Web API to Azure

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Adjust based on your .NET version

      - name: Restore dependencies
        run: dotnet restore ./Tennis.API/Tennis.API.csproj

      - name: Build
        run: dotnet build ./Tennis.API/Tennis.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Tennis.API/Tennis.API.csproj --configuration Release --output ./output

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'ZiliAtelierTest'  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
